@include('frontend/Common/header')
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    @if($flag == 1)
      @include('frontend/Componets/home')
    @elseif($flag == 2)
      @include('frontend/Componets/Product_List')
    @elseif($flag == 3)
        @include('frontend/Componets/Portal_list')
    @elseif($flag == 4)
        @include('frontend/Componets/Add_Product')
    @elseif($flag == 5)
        @include('frontend/Componets/Visitor_List')
    @elseif($flag == 6)
        @include('frontend/Componets/Edit_Portal')
    @elseif($flag == 7)
        @include('frontend/Componets/Edit_Product')
    @elseif($flag == 8)
        @include('frontend/Componets/Client_List')    
    @elseif($flag == 9)
        @include('frontend/Componets/Usertype')
    @elseif($flag == 10)
        @include('frontend/Componets/Edit_Usertype')
    @elseif($flag == 11)
        @include('frontend/Componets/Add_Users')
    @elseif($flag == 12)
        @include('frontend/Componets/Edit_User')
    @elseif($flag == 13)
        @include('frontend/Componets/Profile')
    @elseif($flag == 14)
        @include('frontend/Componets/Comapny_List')
    @elseif($flag == 15)
        @include('frontend/Componets/Edit_Comapny')          
    @endif
</aside><!-- /.right-side -->
@include('frontend/Common/footer')